INSERT INTO `ciclo` (`descripcion`, `idFamilia`, `idGrado`, `idLeyEducativa`) VALUES
('Acceso y Conservación en Instalaciones Deportivas',1, 1, 2),
('Informática de Oficina',2, 1, 2),
('Servicios Administrativos',2, 1, 2),
('Actividades Agropecuarias',3, 1, 2),
('Agro-jardinería y Composiciones Florales',3, 1, 2),
('Aprovechamientos Forestales',3, 1, 2),
('Artes Gráficas',4, 1, 2),
('Servicios Comerciales',5, 1, 2),
('Reforma y Mantenimiento de Edificios',6, 1, 2),
('Electricidad y Electrónica',7, 1, 2),
('Fabricación de Elementos Metálicos',7, 1, 2),
('Instalaciones Electrotécnicas y Mecánica',7, 1, 2),
('Fabricación de Elementos Metálicos',8, 1, 2),
('Fabricación y Montaje',8, 1, 2),
('Instalaciones Electrotécnicas y Mecánica',8, 1, 2),
('Actividades de Panadería y Pastelería',9, 1, 2),
('Alojamiento y Lavandería',9, 1, 2),
('Cocina y Restauración',9, 1, 2),
('Peluquería y Estética',10, 1, 2),
('Actividades de Panadería y Pastelería',12, 1, 2),
('Industrias Alimentarias',12, 1, 2),
('Informática de Oficina',14, 1, 2),
('Informática y Comunicaciones',14, 1, 2),
('Fabricación y Montaje',15, 1, 2),
('Mantenimiento de Viviendas',15, 1, 2),
('Carpintería y Mueble',16, 1, 2),
('Actividades Marítimo-Pesqueras',17, 1, 2),
('Mantenimiento de Embarcaciones Deportivas y de Recreo',17, 1, 2),
('Actividades Domésticas y Limpieza de Edificios',21, 1, 2),
('Arreglo y Reparación de Artículos Textiles y de Piel',22, 1, 2),
('Tapicería y Cortinaje',22, 1, 2),
('Mantenimiento de Embarcaciones Deportivas y de Recreo',23, 1, 2),
('Mantenimiento de Vehículos',23, 1, 2),
('Vidriería y Alfarería',24, 1, 2);
