INSERT INTO `provincia` (`descripcion`) VALUES ('Valencia');
INSERT INTO `provincia` (`descripcion`) VALUES ('Castellón');
INSERT INTO `municipio` (`descripcion`, `idProvincia`) VALUES ('Valencia', 1);
INSERT INTO `municipio` (`descripcion`, `idProvincia`) VALUES ('Morella', 2);
INSERT INTO `municipio` (`descripcion`, `idProvincia`) VALUES ('Mislata', 1);
INSERT INTO `centro` (`idCentro`,`descripcion`,`fpempresa`) VALUES (-1,'--Pincha aqui si el centro no está en la lista--',0);
INSERT INTO `centro` (`descripcion`,`fpempresa`) VALUES ('CIPFP Mislata',1);
INSERT INTO `familia` (`descripcion`) VALUES ('Informática');
INSERT INTO `ciclo` (`descripcion`, `idFamilia`) VALUES ('DAW', 1);
INSERT INTO `ciclo` (`descripcion`, `idFamilia`) VALUES ('ASIR', 1);